name: Deploy to Pantheon
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'web/app/object-cache.php'
      - 'private/scripts/*'
      - 'upstream-configuration/**'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    name: Deploy jazzsequence-fair
    runs-on: ubuntu-latest
    env:
      git_user_name: "Pantheon Robot"
      git_user_email: "bot@getpantheon.com"
    concurrency:
      group: ${{ github.workflow }}-main
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          coverage: none

      - name: Setup Git Config
        run: |
          git config --global user.name "${{ env.git_user_name }}"
          git config --global user.email "${{ env.git_user_email }}"

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          git add -A

      - name: Run PHP CodeSniffer
        run: composer lint:phpcs 

      - name: Push to Pantheon
        uses: pantheon-systems/push-to-pantheon@0.7.0
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          machine_token: ${{ secrets.TERMINUS_TOKEN }}
          site: cxr-jazzsequence-fair
          git_user_name: ${{ env.git_user_name }}
          git_user_email: ${{ env.git_user_email }}
          git_commit_message: "ðŸ¤– Commit build assets"
      
  